export const easy = {
  'United States': 'Washington D.C.',
  'China': 'Beijing',
  'India': 'New Delhi',
  'Brazil': 'Brasilia',
  'Russia': 'Moscow',
  'United Kingdom': 'London',
  'France': 'Paris',
  'Germany': 'Berlin',
  'Japan': 'Tokyo',
  'Canada': 'Ottawa',
  'Pakistan': 'Islamabad',
  'Australia': 'Canberra',
};

export const hard = {
  'United States': 'Washington D.C.',
  'China': 'Beijing',
  'India': 'New Delhi',
  'Brazil': 'Brasilia',
  'Russia': 'Moscow',
  'United Kingdom': 'London',
  'France': 'Paris',
  'Germany': 'Berlin',
  'Japan': 'Tokyo',
  'Canada': 'Ottawa',
  'Australia': 'Canberra',
  'South Africa': 'Pretoria, Bloemfontein, Cape Town',
  'Mexico': 'Mexico City',
  'Argentina': 'Buenos Aires',
  'Italy': 'Rome',
  'Spain': 'Madrid',
  'Türkiye (Turkey)': 'Ankara',
  'Saudi Arabia': 'Riyadh',
  'Iran': 'Tehran',
  'Egypt': 'Cairo',
  'Nigeria': 'Abuja',
  'Kenya': 'Nairobi',
  'South Korea': 'Seoul',
  'Indonesia': 'Jakarta',
  'Thailand': 'Bangkok',
  'Vietnam': 'Hanoi',
  'Malaysia': 'Kuala Lumpur',
  'Singapore': 'Singapore',
  'Philippines': 'Manila',
  'Pakistan': 'Islamabad',
  'Afghanistan': 'Kabul',
  'Iraq': 'Baghdad',
  'Israel / Palestine': 'Jerusalem',
  'United Arab Emirates': 'Abu Dhabi',
  'Qatar': 'Doha',
  'Kuwait': 'Kuwait City',
  'Oman': 'Muscat',
  'Yemen': "Sana'a",
  'Morocco': 'Rabat',
  'Algeria': 'Algiers',
};
