import { shuffleArray } from '@/utils';

export const getRandomSubObject = (
  obj: { [key: string]: string },
  num: number,
) => {
  const arr = shuffleArray(Object.keys(obj));
  const randomKeys = arr.slice(0, num);
  const newObj = {};
  randomKeys.forEach((key: string) => {
    // @ts-expect-error weird error
    newObj[key] = obj[key];
  });
  return newObj;
};

export const easy = {
  'United States': 'Washington D.C.',
  'China': 'Beijing',
  'India': 'New Delhi',
  'Brazil': 'Brasilia',
  'Russia': 'Moscow',
  'United Kingdom': 'London',
  'France': 'Paris',
  'Germany': 'Berlin',
  'Japan': 'Tokyo',
  'Canada': 'Ottawa',
  'Australia': 'Canberra',
  'South Africa': 'Pretoria, Bloemfontein, Cape Town',
  'Mexico': 'Mexico City',
  'Argentina': 'Buenos Aires',
  'Italy': 'Rome',
  'Spain': 'Madrid',
  'Türkiye (Turkey)': 'Ankara',
  'Saudi Arabia': 'Riyadh',
  'Iran': 'Tehran',
  'Egypt': 'Cairo',
  'Nigeria': 'Abuja',
  'Kenya': 'Nairobi',
  'South Korea': 'Seoul',
  'Indonesia': 'Jakarta',
  'Thailand': 'Bangkok',
  'Vietnam': 'Hanoi',
  'Malaysia': 'Kuala Lumpur',
  'Philippines': 'Manila',
  'Pakistan': 'Islamabad',
  'Afghanistan': 'Kabul',
  'Iraq': 'Baghdad',
  'Palestine': 'Jerusalem',
  'United Arab Emirates': 'Abu Dhabi',
  'Qatar': 'Doha',
  'Kuwait': 'Kuwait City',
  'Oman': 'Muscat',
  'Yemen': "Sana'a",
  'Morocco': 'Rabat',
  'Algeria': 'Algiers',
};

export const hard = {
  'Afghanistan': 'Kabul',
  'Albania': 'Tirana',
  'Algeria': 'Algiers',
  'Andorra': 'Andorra la Vella',
  'Angola': 'Luanda',
  'Antigua and Barbuda': "Saint John's",
  'Argentina': 'Buenos Aires',
  'Armenia': 'Yerevan',
  'Australia': 'Canberra',
  'Austria': 'Vienna',
  'Azerbaijan': 'Baku',
  'Bahamas': 'Nassau',
  'Bahrain': 'Manama',
  'Bangladesh': 'Dhaka',
  'Barbados': 'Bridgetown',
  'Belarus': 'Minsk',
  'Belgium': 'Brussels',
  'Belize': 'Belmopan',
  'Benin': 'Porto Novo',
  'Bhutan': 'Thimphu',
  'Bolivia': 'La Paz (administrative), Sucre (official)',
  'Bosnia and Herzegovina': 'Sarajevo',
  'Botswana': 'Gaborone',
  'Brazil': 'Brasilia',
  'Brunei': 'Bandar Seri Begawan',
  'Bulgaria': 'Sofia',
  'Burkina Faso': 'Ouagadougou',
  'Burundi': 'Gitega',
  'Cambodia': 'Phnom Penh',
  'Cameroon': 'Yaounde',
  'Canada': 'Ottawa',
  'Cape Verde': 'Praia',
  'Central African Republic': 'Bangui',
  'Chad': "N'Djamena",
  'Chile': 'Santiago',
  'China': 'Beijing',
  'Colombia': 'Bogota',
  'Comoros': 'Moroni',
  'Congo, Democratic Republic of the': 'Kinshasa',
  'Congo, Republic of the': 'Brazzaville',
  'Costa Rica': 'San Jose',
  "Côte d'Ivoire (Ivory Coast)": 'Yamoussoukro',
  'Croatia': 'Zagreb',
  'Cuba': 'Havana',
  'Cyprus': 'Nicosia',
  'Czech Republic (Czechia)': 'Prague',
  'Denmark': 'Copenhagen',
  'Dominica': 'Roseau',
  'Dominican Republic': 'Santo Domingo',
  'East Timor': 'Dili',
  'Ecuador': 'Quito',
  'Egypt': 'Cairo',
  'El Salvador': 'San Salvador',
  'Equatorial Guinea': 'Malabo',
  'Eritrea': 'Asmara',
  'Estonia': 'Tallinn',
  'Eswatini (Swaziland)': 'Mbabana',
  'Ethiopia': 'Addis Ababa',
  'Federated States of Micronesia': 'Palikir',
  'Fiji': 'Suva',
  'Finland': 'Helsinki',
  'France': 'Paris',
  'Gabon': 'Libreville',
  'Gambia': 'Banjul',
  'Georgia': 'Tbilisi',
  'Germany': 'Berlin',
  'Ghana': 'Accra',
  'Greece': 'Athens',
  'Grenada': "Saint George's",
  'Guatemala': 'Guatemala City',
  'Guinea': 'Conakry',
  'Guinea-Bissau': 'Bissau',
  'Guyana': 'Georgetown',
  'Haiti': 'Port au Prince',
  'Honduras': 'Tegucigalpa',
  'Hungary': 'Budapest',
  'Iceland': 'Reykjavik',
  'India': 'New Delhi',
  'Indonesia': 'Jakarta',
  'Iran': 'Tehran',
  'Iraq': 'Baghdad',
  'Ireland': 'Dublin',
  'Palestine': 'Jerusalem',
  'Italy': 'Rome',
  'Jamaica': 'Kingston',
  'Japan': 'Tokyo',
  'Jordan': 'Amman',
  'Kazakhstan': 'Astanas',
  'Kenya': 'Nairobi',
  'Kiribati': 'Tarawa Atoll',
  'Kosovo': 'Pristina',
  'Kuwait': 'Kuwait City',
  'Kyrgyzstan': 'Bishkek',
  'Laos': 'Vientiane',
  'Latvia': 'Riga',
  'Lebanon': 'Beirut',
  'Lesotho': 'Maseru',
  'Liberia': 'Monrovia',
  'Libya': 'Tripoli',
  'Liechtenstein': 'Vaduz',
  'Lithuania': 'Vilnius',
  'Madagascar': 'Antananarivo',
  'Malawi': 'Lilongwe',
  'Malaysia': 'Kuala Lumpur',
  'Maldives': 'Male',
  'Mali': 'Bamako',
  'Malta': 'Valletta',
  'Marshall Islands': 'Majuro',
  'Mauritania': 'Nouakchott',
  'Mauritius': 'Port Louis',
  'Mexico': 'Mexico City',
  'Moldova': 'Chisinau',
  'Mongolia': 'Ulaanbaatar',
  'Montenegro': 'Podgorica',
  'Morocco': 'Rabat',
  'Mozambique': 'Maputo',
  'Myanmar (Burma)': 'Nay Pyi Taw',
  'Namibia': 'Windhoek',
  'Nauru': 'No official capital',
  'Nepal': 'Kathmandu',
  'Netherlands': 'Amsterdam',
  'New Zealand': 'Wellington',
  'Nicaragua': 'Managua',
  'Niger': 'Niamey',
  'Nigeria': 'Abuja',
  'North Korea': 'Pyongyang',
  'North Macedonia (Macedonia)': 'Skopje',
  'Northern Ireland': 'Belfast',
  'Norway': 'Oslo',
  'Oman': 'Muscat',
  'Pakistan': 'Islamabad',
  'Palau': 'Melekeok',
  'Panama': 'Panama City',
  'Papua New Guinea': 'Port Moresby',
  'Paraguay': 'Asuncion',
  'Peru': 'Lima',
  'Philippines': 'Manila',
  'Poland': 'Warsaw',
  'Portugal': 'Lisbon',
  'Qatar': 'Doha',
  'Romania': 'Bucharest',
  'Russia': 'Moscow',
  'Rwanda': 'Kigali',
  'Saint Kitts and Nevis': 'Basseterre',
  'Saint Lucia': 'Castries',
  'Saint Vincent and the Grenadines': 'Kingstown',
  'Samoa': 'Apia',
  'Sao Tome and Principe': 'Sao Tome',
  'Saudi Arabia': 'Riyadh',
  'Scotland': 'Edinburgh',
  'Senegal': 'Dakar',
  'Serbia': 'Belgrade',
  'Seychelles': 'Victoria',
  'Sierra Leone': 'Freetown',
  'Slovakia': 'Bratislava',
  'Slovenia': 'Ljubljana',
  'Solomon Islands': 'Honiara',
  'Somalia': 'Mogadishu',
  'South Africa': 'Pretoria, Bloemfontein, Cape Town',
  'South Korea': 'Seoul',
  'South Sudan': 'Juba',
  'Spain': 'Madrid',
  'Sri Lanka': 'Sri Jayawardenapura Kotte',
  'Sudan': 'Khartoum',
  'Suriname': 'Paramaribo',
  'Sweden': 'Stockholm',
  'Switzerland': 'Bern',
  'Syria': 'Damascus',
  'Taiwan': 'Taipei',
  'Tajikistan': 'Dushanbe',
  'Tanzania': 'Dodoma',
  'Thailand': 'Bangkok',
  'Togo': 'Lome',
  'Tonga': "Nuku'alofa",
  'Trinidad and Tobago': 'Port of Spain',
  'Tunisia': 'Tunis',
  'Türkiye (Turkey)': 'Ankara',
  'Turkmenistan': 'Ashgabat',
  'Tuvalu': 'Funafuti',
  'Uganda': 'Kampala',
  'Ukraine': 'Kyiv or Kiev',
  'United Arab Emirates': 'Abu Dhabi',
  'England / United Kingdom': 'London',
  'United States': 'Washington D.C.',
  'Uruguay': 'Montevideo',
  'Uzbekistan': 'Tashkent',
  'Vanuatu': 'Port Vila',
  'Venezuela': 'Caracas',
  'Vietnam': 'Hanoi',
  'Wales': 'Cardiff',
  'Yemen': "Sana'a",
  'Zambia': 'Lusaka',
  'Zimbabwe': 'Harare',
};
